=== statox/XML_M1_S7/TP/TP1/exercice1/film.dtd
<!-- DTD d'un film  -->

<!--
<!ELEMENT film  (notes, genres, realisateur , acteurs , description , horaires )> 
-->
<!-- Chaque film doit contenir un arbre d'horaire -->

<!ELEMENT film  (notes|genres|realisateur|acteurs|description|horaires)+> 

<!-- Chaque film doit contenir un titre, c'est indique par le mot cle #REQUIRED apres titre -->
<!ATTLIST film
        titre 		CDATA 	#REQUIRED       
	duree 		CDATA 	#REQUIRED
	annee 	CDATA 	#REQUIRED
	langue 	CDATA 	#REQUIRED
	presse 	CDATA 	#IMPLIED
	spectateurs 	CDATA 	#IMPLIED
>


<!ELEMENT notes (presse?, spectateurs?)>	<!-- Les notes presse et spectateurs sont optionnelles -->
<!ELEMENT presse (#PCDATA)>
<!ELEMENT spectateurs (#PCDATA)>

<!ELEMENT genres (genre+)>
<!ELEMENT genre (#PCDATA)>

<!ELEMENT realisateur  ( nom , prenom )>

<!ELEMENT acteurs  ( acteur+ )>
<!ELEMENT acteur  ( nom , prenom )>

<!ELEMENT nom  ( #PCDATA )>
<!ELEMENT prenom  ( #PCDATA )>

<!ELEMENT description  ( #PCDATA )>

<!ELEMENT horaires  ( horaire+ )>           <!-- L'arbre d'horaires doit contenir au moins un horaire -->
<!ELEMENT horaire  ( jours , heures )>

<!ELEMENT jours  ( jour+ )>
<!ELEMENT jour  ( #PCDATA )>

<!ELEMENT heures  ( heure+ )>
<!ELEMENT heure  ( #PCDATA )>

=== statox/XML_M1_S7/TP/TP1/exercice1/film_brigades_du_tigre.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE film SYSTEM "film.dtd">

<film titre="Les Brigades du Tigre" duree="125" annee="2005" langue="VF" presse="5">
        <genres>
	         <genre>Policier</genre>
        </genres>
        <notes>
          <!--<presse>10</presse>-->
		<spectateurs>5</spectateurs>
	</notes>

	<realisateur>
		<nom>Cornuau</nom>
		<prenom>Jérome</prenom>
	</realisateur>
	<acteurs>
		<acteur>
			<nom>Cornillac</nom>
			<prenom>Clovis</prenom>
		</acteur>
		<acteur>
			<nom>Kruger</nom>
			<prenom>Diane</prenom>
		</acteur>
		<acteur>
			<nom>Baer</nom>
			<prenom>Edouar</prenom>
		</acteur>
	</acteurs>
	<description>Les aventures du commissaire Valentin et des inspecteurs Terrasson et Pujol, membres des Brigades mobiles, corps spécial de la police française créé avant la Première Guerre mondiale.
	</description>
	<horaires>
		<horaire>
			<jours>
				<jour>Mercredi</jour>
				<jour>Samedi</jour>
			</jours>
			<heures>
				<heure>14h00</heure>
				<heure>16h40</heure>
				<heure>19h40</heure>
				<heure>22h10</heure>
			</heures>
		</horaire>
		<horaire>
			<jours>
				<jour>Lundi</jour>
				<jour>Mardi</jour>
				<jour>Jeudi</jour>
				<jour>Vendredi</jour>
			</jours>
			<heures>
				<heure>14h00</heure>
				<heure>19h40</heure>
				<heure>22h10</heure>
			</heures>
		</horaire>
		<horaire>
			<jours>
				<jour>Dimanche</jour>
			</jours>
			<heures>
				<heure>10h20</heure>
				<heure>14h00</heure>
				<heure>16h40</heure>
				<heure>20h20</heure>
			</heures>
		</horaire>
	</horaires>
</film>
