=== statox/XML_M1_S7/TP/TP3/Exemple_workspaceEclipse_DOM_SAX/Tp_SAX/XMLFile/test10.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT bibliotheque (livre+)>
<!ELEMENT date_sortie (#PCDATA)>
<!ELEMENT livre (auteur, date_sortie, nbre_page)>
<!ELEMENT nbre_page (#PCDATA)>

=== statox/XML_M1_S7/TP/TP3/Exemple_workspaceEclipse_DOM_SAX/Tp_SAX/XMLFile/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--!DOCTYPE bibliotheque SYSTEM "C:\jwsdp-1.2\jaxb\bin\bib1.dtd" -->
<!DOCTYPE bibliotheque SYSTEM "test10.dtd">
<bibliotheque>
	<livre>
		<auteur>Socrate</auteur>
		<date_sortie>10-10-2000</date_sortie>
		<nbre_page>62</nbre_page>
	</livre>
	<livre>
		<auteur>Marceau</auteur>
		<date_sortie>11-10-2000</date_sortie>
		<nbre_page>50</nbre_page>
	</livre>
	<livre>
		<auteur>La fontaine</auteur>
		<date_sortie>12-10-2000</date_sortie>
		<nbre_page>100</nbre_page>
	</livre>
</bibliotheque>
