<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE list [ 
	<!ELEMENT list (man | woman)*>
	<!ELEMENT man (sons, daughters)>
	<!ATTLIST man name CDATA #REQUIRED>
	<!ELEMENT woman (sons, daughters)>
	<!ATTLIST woman name CDATA #REQUIRED>
	<!ELEMENT sons (man)*>
	<!ELEMENT daughters (woman)*>
]>

<list>
	<man name="Julien">
		<sons>
		</sons>
		<daughters>
			<woman name="Sophie">
				<sons>
				</sons>
				<daughters>
				</daughters>
			</woman>

			<woman name="Ursule">
				<sons>
				</sons>
				<daughters>
				</daughters>
			</woman>

		</daughters>
	</man>

	<woman name="Marie">
		<sons>
			<man name="Joseph">
				<sons>
				</sons>
				<daughters>
					<woman name="Marie">
						<sons>
						</sons>
						<daughters>
						</daughters>
					</woman>

				</daughters>
			</man>

		</sons>
		<daughters>
		</daughters>
	</woman>

</list>
